#!/usr/bin/env python3
"""Generate the ALIEN STRIKE voice files.

Reads every voice line from the game data (via tools/export_lines.mjs), synthesises
it offline with Piper neural TTS, applies a per-speaker processing chain with ffmpeg
(ship AI / radio command / intel / survivor), writes audio/voice/<id>.mp3 and
rebuilds data/voice_manifest.js (ids + durations).

Usage:
  python3 tools/gen_voice.py --models <dir with piper .onnx voices> [--only id1,id2] [--force]

Voices used (Piper v0.0.2 release): en-us-lessac-medium (ship), en-us-ryan-medium
(command), en-gb-alan-low (intel), en-us-amy-low (survivor). Any recorded file placed
at audio/voice/<id>.mp3 replaces the generated one: existing files are kept unless
--force is given, and every run rebuilds the manifest.
"""
import argparse, json, os, subprocess, sys, tempfile, concurrent.futures

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VOICE = {
    'ship': ('en-us-lessac-medium', 1.04, 'highpass=f=170,lowpass=f=7600,aecho=0.8:0.55:7:0.25,acompressor=threshold=-20dB:ratio=3:attack=5:release=80,volume=1.35'),
    'command': ('en-us-ryan-medium', 0.97, 'highpass=f=330,lowpass=f=3300,acompressor=threshold=-24dB:ratio=6:attack=4:release=60,volume=2.0'),
    'brief': ('en-us-ryan-medium', 1.0, 'highpass=f=200,lowpass=f=5200,acompressor=threshold=-22dB:ratio=4:attack=5:release=80,volume=1.6'),
    'intel': ('en-gb-alan-low', 1.0, 'highpass=f=260,lowpass=f=4200,acompressor=threshold=-22dB:ratio=5:attack=5:release=70,volume=1.8'),
    'survivor': ('en-us-amy-low', 0.95, 'highpass=f=380,lowpass=f=3000,acompressor=threshold=-24dB:ratio=6:attack=3:release=50,volume=2.1'),
}
NOISE = {'command': 0.012, 'brief': 0.006, 'intel': 0.01, 'survivor': 0.02, 'ship': 0.0}

def duration(path):
    out = subprocess.run(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=nw=1:nk=1', path], capture_output=True, text=True).stdout.strip()
    try: return round(float(out), 2)
    except ValueError: return None

def make(id_, line, models, outdir, force):
    out = os.path.join(outdir, id_ + '.mp3')
    if os.path.exists(out) and not force:
        return id_, duration(out)
    kind = 'brief' if id_.startswith('brief_') else line['s']
    model, ls, chain = VOICE.get(kind, VOICE['command'])
    with tempfile.TemporaryDirectory() as td:
        wav = os.path.join(td, 'v.wav')
        p = subprocess.run([sys.executable, '-m', 'piper', '-m', os.path.join(models, model + '.onnx'), '-f', wav, '--length-scale', str(ls)], input=line['t'], capture_output=True, text=True)
        if p.returncode != 0 or not os.path.exists(wav):
            print('piper failed', id_, p.stderr[-300:]); return id_, None
        n = NOISE.get(kind, 0)
        if n > 0:
            fc = f'[0:a]{chain},apad=pad_dur=0.15[v];anoisesrc=c=pink:a={n}:r=22050[n];[v][n]amix=inputs=2:duration=first:weights=1 1,afade=t=in:d=0.04,loudnorm=I=-17:TP=-1.5:LRA=11,aresample=22050[o]'
        else:
            fc = f'[0:a]{chain},apad=pad_dur=0.15,loudnorm=I=-17:TP=-1.5:LRA=11,aresample=22050[o]'
        q = subprocess.run(['ffmpeg', '-v', 'error', '-y', '-i', wav, '-filter_complex', fc, '-map', '[o]', '-ac', '1', '-ar', '22050', '-c:a', 'libmp3lame', '-b:a', '48k', out], capture_output=True, text=True)
        if q.returncode != 0:
            print('ffmpeg failed', id_, q.stderr[-300:]); return id_, None
    return id_, duration(out)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--models', required=True)
    ap.add_argument('--only', default='')
    ap.add_argument('--force', action='store_true')
    ap.add_argument('--jobs', type=int, default=4)
    a = ap.parse_args()
    lines = json.loads(subprocess.run(['node', os.path.join(ROOT, 'tools', 'export_lines.mjs')], capture_output=True, text=True, check=True).stdout)
    outdir = os.path.join(ROOT, 'audio', 'voice'); os.makedirs(outdir, exist_ok=True)
    ids = [i for i in lines if not a.only or i in a.only.split(',')]
    res = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=a.jobs) as ex:
        for id_, d in ex.map(lambda i: make(i, lines[i], a.models, outdir, a.force), ids):
            if d: res[id_] = d
    # manifest lists every line with an existing file
    man = {}
    for i in lines:
        f = os.path.join(outdir, i + '.mp3')
        if os.path.exists(f): man[i] = {'d': res.get(i) or duration(f)}
    with open(os.path.join(ROOT, 'data', 'voice_manifest.js'), 'w') as fh:
        fh.write('/* generated by tools/gen_voice.py — ids with recorded audio and their durations (seconds) */\n')
        fh.write("'use strict';\nwindow.AS = window.AS || {}; AS.Data = AS.Data || {};\n")
        fh.write('AS.Data.voiceFiles = ' + json.dumps(man, separators=(',', ':')) + ';\n')
    print(len(man), 'voice files in manifest')

if __name__ == '__main__':
    main()
