/* ALIEN STRIKE — World 10: THE FIRST WORLD (allied forces; the final operation). */
'use strict';
(function (AS) {
  const L = AS.L;

  AS.Levels.add({
    id: 'w10m1', world: 10, index: 1, name: 'LANDFALL', region: 'The Sanctum Coast',
    map: { w: 6400, h: 6400, seed: 211 },
    start: { x: 3200, y: 5900, angle: -Math.PI / 2 }, extraction: { x: 3200, y: 6060, r: 75 },
    briefing: {
      tagline: 'Silence the sky-denial guns so the fleet can land.',
      danger: 5,
      situation: "This is it: the First World, the homeworld of the Choir. The FRC fleet is in orbit with everything we have, but four sky-denial guns on the Sanctum Coast will tear our landers apart. Destroy all four. Once the sky is clear, the first wave of armour lands on your LZ — hold it until the beachhead is secure. Allied Lancer gunships are flying with you. This is no longer a scavenger run, Vesper. This is a war.",
      narration: 'Vesper, this is the First World. The fleet is in orbit, but four sky-denial guns will shred our landers. Destroy all four. Then hold the landing zone while the first armour wave comes down. Allied gunships are flying with you. This is no longer a scavenger run. This is a war.',
      threats: ['Sky-denial flak guns', 'Choir lancers, titans and seraph fighters', 'Living engines', 'Heavy resistance everywhere'],
      intel: ['Each sky-denial gun is shielded by a local generator.', 'Allied gunships will follow and support you.'],
      marks: [{ x: 1400, y: 2000, label: 'AA', col: '#ff9a5a' }, { x: 3200, y: 1200, label: 'AA', col: '#ff9a5a' }, { x: 5000, y: 2000, label: 'AA', col: '#ff9a5a' }, { x: 4200, y: 3600, label: 'AA', col: '#ff9a5a' }],
    },
    rewards: { salvage: 1500, tech: 4 },
    reinforcements: { comms: ['cmd'], squads: [['seraph', 'seraph'], ['choirlancer', 'choirlancer'], ['behemoth']], from: [{ x: 300, y: 300 }, { x: 6100, y: 300 }, { x: 3200, y: 200 }], delay: 8, cooldown: 35, max: 6 },
    lines: {
      w10m1_intro: { t: 'All wings, this is Halcyon. Vesper leads. Take down those guns.', s: 'command' },
      w10m1_gun: { t: 'Gun down! Landers adjusting approach!', s: 'command' },
      w10m1_clear: { t: 'Sky is clear! First wave inbound to your LZ — hold it for sixty seconds!', s: 'command' },
      w10m1_landed: { t: 'Armour is on the ground. We have a beachhead on the First World.', s: 'command' },
    },
    entities: [
      { t: 'unit', k: 'ally_gunship', x: 3100, y: 5600, team: 'player', active: true }, { t: 'unit', k: 'ally_gunship', x: 3300, y: 5600, team: 'player', active: true },
      { t: 'struct', k: 'aagun', id: 'aa1', x: 1400, y: 2000, shieldedBy: ['aa1sg'] }, { t: 'struct', k: 'shieldgen', id: 'aa1sg', x: 1200, y: 2200 },
      { t: 'struct', k: 'aagun', id: 'aa2', x: 3200, y: 1200, shieldedBy: ['aa2sg'] }, { t: 'struct', k: 'shieldgen', id: 'aa2sg', x: 3450, y: 1350 },
      { t: 'struct', k: 'aagun', id: 'aa3', x: 5000, y: 2000, shieldedBy: ['aa3sg'] }, { t: 'struct', k: 'shieldgen', id: 'aa3sg', x: 5250, y: 2200 },
      { t: 'struct', k: 'aagun', id: 'aa4', x: 4200, y: 3600, shieldedBy: ['aa4sg'] }, { t: 'struct', k: 'shieldgen', id: 'aa4sg', x: 4000, y: 3800 },
      { t: 'struct', k: 'turret_heavy', x: 1500, y: 2250 }, { t: 'struct', k: 'turret_heavy', x: 3000, y: 1400 }, { t: 'struct', k: 'turret_heavy', x: 4800, y: 2250 }, { t: 'struct', k: 'turret_heavy', x: 4400, y: 3800 },
      { t: 'struct', k: 'comms', id: 'cmd', x: 3200, y: 600 },
      { t: 'unit', k: 'choirlancer', x: 2400, y: 3000, n: 2, patrol: [[2400, 3000], [3600, 2600], [3200, 3800]] },
      { t: 'unit', k: 'titan', x: 3200, y: 2200 },
      { t: 'zone', id: 'garden', x: 600, y: 4200, r: 220 }, ...L.cache(600, 4200, ['tech', 'tech', 'special', 'repair'], { hidden: true }),
      ...L.fill(211, { w: 6400, h: 6400, units: [['choirlancer', 3, [1, 2]], ['seraph', 3, [2, 2]], ['behemoth', 2, [1, 1]], ['thrall', 4, [3, 5]]], obstacles: 30, supplies: ['ammo', 'missiles', 'repair', 'shield', 'special', 'salvage', 'fuel'] }),
    ],
    objectives: [
      { id: 'guns', type: 'destroy', targets: ['aa1', 'aa2', 'aa3', 'aa4'], text: 'Destroy the sky-denial guns', short: 'Destroy the four sky-denial guns' },
      { id: 'hold', type: 'defend', target: 'lz', duration: 60, text: 'Hold the landing zone for the first wave', short: 'Hold the LZ (1:00)', locked: true },
      { id: 'cmd', type: 'destroy', targets: ['cmd'], text: 'Destroy the coastal command relay', short: 'Destroy the command relay', cat: 'secondary', reward: 250 },
      { id: 'garden', type: 'discover', zone: 'garden', text: 'Find the first garden', short: 'Find the first garden', cat: 'hidden' },
    ],
    triggers: [
      { when: { time: 3 }, do: [{ say: 'w10m1_intro' }] },
      { when: { destroyedAny: ['aa1', 'aa2', 'aa3', 'aa4'] }, do: [{ say: 'w10m1_gun' }] },
      { when: { objective: 'guns' }, do: [{ say: 'w10m1_clear' }, { activate: 'hold' }, { music: 'combat' }] },
      { when: { objective: 'guns' }, delay: 8, do: [{ wave: { k: 'choirlancer', n: 3, x: 3200, y: 3400, tx: 3200, ty: 6000 } }, { wave: { k: 'seraph', n: 2, x: 600, y: 5000, tx: 3200, ty: 6000, say: false } }] },
      { when: { objective: 'guns' }, delay: 30, do: [{ wave: { k: 'behemoth', n: 1, x: 5800, y: 5400, tx: 3200, ty: 6000 } }, { wave: { k: 'thrall', n: 6, x: 5600, y: 5600, tx: 3200, ty: 6000, say: false } }] },
      { when: { objective: 'guns' }, delay: 50, do: [{ spawn: [{ t: 'unit', k: 'ally_tank', x: 3000, y: 5800, team: 'player', active: true }, { t: 'unit', k: 'ally_tank', x: 3400, y: 5800, team: 'player', active: true }] }] },
      { when: { objective: 'hold' }, do: [{ say: 'w10m1_landed' }, { music: 'none' }] },
    ],
  });

  AS.Levels.add({
    id: 'w10m2', world: 10, index: 2, name: 'THE LONG WALK', region: 'The Processional',
    map: { w: 6400, h: 6400, seed: 223 },
    start: { x: 600, y: 5900, angle: -Math.PI / 4 }, extraction: { x: 480, y: 6060, r: 75 },
    briefing: {
      tagline: 'Escort the armoured column and kill the Archon commanding the Processional.',
      danger: 5,
      situation: "The road to the Heart of the Choir runs down the Processional, a ceremonial avenue three kilometres long and lined with living statues. Our armoured column is rolling down it now. The Choir commander here — an elite titan our crews call the Archon — is co-ordinating the defence. Kill it. Three lance relays along the avenue feed power to the planetary weapon; destroy them too. Get at least two of our Warden tanks to the gate at the far end.",
      narration: 'Vesper, our armour is rolling down the Processional toward the Heart. Get at least two tanks to the far gate. The Archon, an elite titan, is commanding the defence. Kill it. And destroy the three lance relays along the avenue. They feed the planetary weapon.',
      threats: ['THE ARCHON — elite titan commander', 'Lance relays — heavily defended', 'Choir lancers, seraphs, living engines'],
      intel: ['The column halts when hostiles block the road.', 'Forward pad Quebec halfway down the avenue.'],
      marks: [{ x: 3200, y: 3200, label: 'ARCHON', col: '#ff5a3a' }, { x: 5800, y: 600, label: 'GATE', col: '#7dff9a' }],
    },
    rewards: { salvage: 1600, tech: 4 },
    reinforcements: { comms: [], squads: [['seraph', 'seraph', 'seraph'], ['choirlancer', 'choirlancer'], ['behemoth']], from: [{ x: 6100, y: 300 }, { x: 300, y: 300 }], delay: 6, cooldown: 30, max: 7 },
    lines: {
      w10m2_intro: { t: 'Column is rolling. Vesper, clear the road and find the Archon.', s: 'command' },
      w10m2_archon: { t: "That's the Archon. It's directing everything. Kill it!", s: 'command' },
      w10m2_archon_dead: { t: "Archon is down! Their defence is falling apart!", s: 'command' },
      w10m2_relay: { t: 'Lance relay destroyed. The planetary weapon is losing power.', s: 'command' },
      w10m2_gate: { t: 'Lead tank has reached the gate!', s: 'command' },
    },
    entities: [
      ...L.fob('fob', 3000, 3600),
      { t: 'convoy', id: 'column', units: ['ally_tank', 'ally_tank', 'ally_tank'], team: 'player', x: 900, y: 5600, spacing: 80, start: false,
        path: [[1500, 5000], [2200, 4400], [2900, 3800], [3500, 3100], [4100, 2400], [4800, 1700], [5400, 1100], [5800, 650]] },
      { t: 'unit', k: 'ally_gunship', x: 800, y: 5700, team: 'player', active: true },
      { t: 'unit', k: 'titan', id: 'archon', x: 3200, y: 3200 },
      { t: 'zone', id: 'archonzone', x: 3200, y: 3200, r: 700 },
      { t: 'struct', k: 'power', id: 'lr1', x: 2000, y: 3900, hp: 320 }, { t: 'struct', k: 'turret_heavy', x: 1900, y: 3700 }, { t: 'struct', k: 'turret_heavy', x: 2200, y: 4000 },
      { t: 'struct', k: 'power', id: 'lr2', x: 3800, y: 2200, hp: 320 }, { t: 'struct', k: 'turret_heavy', x: 3700, y: 2000 }, { t: 'struct', k: 'turret_heavy', x: 4000, y: 2300 },
      { t: 'struct', k: 'power', id: 'lr3', x: 5300, y: 1700, hp: 320 }, { t: 'struct', k: 'turret_heavy', x: 5200, y: 1500 }, { t: 'struct', k: 'turret_heavy', x: 5500, y: 1800 },
      { t: 'obstacle', k: 'column', x: 1700, y: 4700 }, { t: 'struct', k: 'obelisk', x: 2600, y: 4000 }, { t: 'struct', k: 'obelisk', x: 3400, y: 2700 }, { t: 'struct', k: 'obelisk', x: 4500, y: 2000 }, { t: 'struct', k: 'obelisk', x: 5100, y: 1300 },
      { t: 'zone', id: 'ossuary', x: 6000, y: 6000, r: 220 }, ...L.cache(6000, 6000, ['tech', 'tech', 'special'], { hidden: true }),
      ...L.fill(223, { w: 6400, h: 6400, units: [['choirlancer', 3, [1, 2]], ['seraph', 3, [2, 2]], ['behemoth', 2, [1, 1]], ['thrall', 4, [3, 5]]], obstacles: 26 }),
    ],
    objectives: [
      { id: 'column', type: 'escort', convoy: 'column', required: 2, text: 'Escort the armoured column to the gate', short: 'Get 2 tanks to the gate', marker: 'COLUMN' },
      { id: 'archon', type: 'kill', targets: ['archon'], text: 'Kill the Archon', short: 'Kill the Archon' },
      { id: 'relays', type: 'destroy', targets: ['lr1', 'lr2', 'lr3'], text: 'Destroy the lance relays', short: 'Destroy the three lance relays' },
      { id: 'ossuary', type: 'discover', zone: 'ossuary', text: 'Find the ossuary', short: 'Find the ossuary', cat: 'hidden' },
    ],
    triggers: [
      { when: { time: 3 }, do: [{ say: 'w10m2_intro' }] },
      { when: { time: 10 }, do: [{ convoy: 'column', act: 'start' }] },
      { when: { enter: 'archonzone' }, do: [{ say: 'w10m2_archon' }] },
      { when: { killed: 'archon' }, do: [{ say: 'w10m2_archon_dead' }] },
      { when: { destroyedAny: ['lr1', 'lr2', 'lr3'] }, do: [{ say: 'w10m2_relay' }] },
      { when: { convoyArrived: 'column' }, do: [{ say: 'w10m2_gate' }] },
    ],
  });

  AS.Levels.add({
    id: 'w10m3', world: 10, index: 3, name: 'HEART OF THE CHOIR', region: 'The Heart', boss: true,
    map: { w: 6800, h: 6800, seed: 233 },
    start: { x: 3400, y: 6300, angle: -Math.PI / 2 }, extraction: { x: 3400, y: 6460, r: 80 },
    briefing: {
      tagline: 'The final assault. Destroy the Heart of the Choir.',
      danger: 5,
      situation: "Everything ends here. The Heart of the Choir is the planetary lance — the weapon that has been killing our ships since the Veil — and the mind that woke every machine on ten worlds. Three Sanctum pylons seal it. The whole fleet is committed: armour on the ground, gunships in the air, and you at the tip of the spear. Break the pylons, then break the Heart. Our pilots shot down over the Sanctum are being held in pens near the pylons; bring them home if you can. Vesper — it has been an honour.",
      narration: 'Vesper, this is the end of the road. The Heart of the Choir is the planetary lance, and the mind behind every machine on ten worlds. Three Sanctum pylons seal it. The whole fleet is with you. Break the pylons, then break the Heart. Our captured pilots are held near the pylons. Bring them home if you can. It has been an honour, Vesper. Make it count.',
      threats: ['THE HEART OF THE CHOIR — planetary lance strikes, endless waves', 'Sanctum pylons', 'Titans, lancers, seraphs, living engines'],
      intel: ['Lance strikes are telegraphed: a violet ring on the ground. Do not be inside it.', 'Pad Romeo behind the allied line.'],
      marks: [{ x: 3400, y: 2600, label: 'HEART', col: '#ff5a3a' }, { x: 2000, y: 3200, label: 'P', col: '#ffc35a' }, { x: 4800, y: 3200, label: 'P', col: '#ffc35a' }, { x: 3400, y: 1300, label: 'P', col: '#ffc35a' }],
    },
    rewards: { salvage: 2500, tech: 5 },
    reinforcements: { comms: [], squads: [['seraph', 'seraph', 'seraph'], ['choirlancer', 'choirlancer', 'choirlancer'], ['titan'], ['behemoth', 'thrall', 'thrall', 'thrall']], from: [{ x: 300, y: 300 }, { x: 6500, y: 300 }, { x: 3400, y: 200 }], delay: 6, cooldown: 28, max: 8 },
    lines: {
      w10m3_intro: { t: 'All forces, Halcyon Actual. This is the hour. Vesper, break those pylons.', s: 'command' },
      w10m3_pylon: { t: 'Pylon down! The Heart is exposed on that side!', s: 'command' },
      w10m3_open: { t: "All pylons down! The Heart is open! Vesper — finish it!", s: 'command' },
      lance_charging: { t: 'Lance charging! Get out of the ring!', s: 'ship' },
      w10m3_pilots: { t: "Fleet pilots! They're alive! Get them out!", s: 'command' },
      w10m3_dead: { t: 'The Heart is gone. Every Choir machine on every world just went silent. Vesper... come home.', s: 'command' },
    },
    entities: [
      ...L.fob('fob', 3400, 5300),
      { t: 'unit', k: 'ally_tank', x: 3000, y: 5600, n: 3, spread: 120, team: 'player', active: true, path: [[3000, 4600], [3200, 3800], [3400, 3300]] },
      { t: 'unit', k: 'ally_tank', x: 3800, y: 5600, n: 2, spread: 120, team: 'player', active: true, path: [[3800, 4600], [3700, 3800], [3500, 3300]] },
      { t: 'unit', k: 'ally_gunship', x: 3300, y: 6000, n: 3, spread: 120, team: 'player', active: true },
      { t: 'struct', k: 'shieldpylon', id: 'p1', x: 2000, y: 3200 }, { t: 'struct', k: 'shieldpylon', id: 'p2', x: 4800, y: 3200 }, { t: 'struct', k: 'shieldpylon', id: 'p3', x: 3400, y: 1300 },
      { t: 'struct', k: 'aagun', x: 2200, y: 3000 }, { t: 'struct', k: 'aagun', x: 4600, y: 3000 }, { t: 'struct', k: 'aagun', x: 3600, y: 1450 },
      { t: 'struct', k: 'turret_heavy', x: 1800, y: 3400 }, { t: 'struct', k: 'turret_heavy', x: 5000, y: 3400 }, { t: 'struct', k: 'turret_heavy', x: 3200, y: 1150 },
      { t: 'boss', k: 'heart', id: 'heart', x: 3400, y: 2600, shieldedBy: ['p1', 'p2', 'p3'], wake: 1100, deathLine: 'w10m3_dead' },
      { t: 'struct', k: 'pen', id: 'pen1', x: 1700, y: 2900 }, { t: 'survivors', id: 'pilots1', x: 1700, y: 2900, n: 3, kind: 'prisoner', label: 'FLEET PILOTS', caged: 'pen1', voice: false },
      { t: 'struct', k: 'pen', id: 'pen2', x: 5100, y: 2900 }, { t: 'survivors', id: 'pilots2', x: 5100, y: 2900, n: 3, kind: 'prisoner', label: 'FLEET PILOTS', caged: 'pen2', voice: false },
      { t: 'zone', id: 'penzone', x: 1700, y: 2900, r: 500 },
      { t: 'unit', k: 'titan', x: 2400, y: 2400 }, { t: 'unit', k: 'titan', x: 4400, y: 2400 },
      ...L.fill(233, { w: 6800, h: 6800, units: [['choirlancer', 4, [1, 2]], ['seraph', 4, [2, 3]], ['behemoth', 2, [1, 1]], ['thrall', 5, [3, 5]]], obstacles: 30, supplies: ['ammo', 'missiles', 'repair', 'shield', 'special', 'fuel', 'salvage'] }),
    ],
    objectives: [
      { id: 'pylons', type: 'destroy', targets: ['p1', 'p2', 'p3'], text: 'Destroy the Sanctum pylons', short: 'Destroy the three Sanctum pylons' },
      { id: 'heart', type: 'boss', targets: ['heart'], text: 'Destroy the Heart of the Choir', short: 'Destroy the Heart of the Choir', marker: 'HEART' },
      { id: 'pilots', type: 'rescue', groups: ['pilots1', 'pilots2'], required: 4, text: 'Rescue the captured fleet pilots', short: 'Rescue the fleet pilots', cat: 'secondary', reward: 400 },
    ],
    triggers: [
      { when: { time: 3 }, do: [{ say: 'w10m3_intro' }, { music: 'combat' }] },
      { when: { destroyedAny: ['p1', 'p2', 'p3'] }, do: [{ say: 'w10m3_pylon' }] },
      { when: { objective: 'pylons' }, do: [{ say: 'w10m3_open' }, { boss: 'heart', act: 'activate' }] },
      { when: { enter: 'penzone' }, do: [{ say: 'w10m3_pilots' }] },
      { when: { time: 40 }, do: [{ wave: { k: 'seraph', n: 3, x: 300, y: 3000, tx: 3400, ty: 4600 } }] },
      { when: { time: 100 }, do: [{ wave: { k: 'behemoth', n: 2, x: 6400, y: 4000, tx: 3400, ty: 4600 } }] },
      { when: { time: 160 }, do: [{ wave: { k: 'titan', n: 1, x: 3400, y: 400, tx: 3400, ty: 3600 } }] },
    ],
  });
})(window.AS);
