/* ALIEN STRIKE — World 2: CRIMSON DUNES (sandstorms blind the scanner). */
'use strict';
(function (AS) {
  const L = AS.L;

  AS.Levels.add({
    id: 'w2m1', world: 2, index: 1, name: 'RED HARVEST', region: 'Hadal Flats',
    map: { w: 6400, h: 6000, seed: 41 },
    start: { x: 600, y: 3000, angle: 0 },
    extraction: { x: 480, y: 3150, r: 70 },
    briefing: {
      tagline: 'Wreck the Choir strip-mining operation.',
      danger: 2,
      situation: 'The Choir are strip-mining the Hadal Flats with three deep drill rigs feeding a refinery. Captured colonists are being worked to death in pens beside the rigs. Burn the operation: all three rigs and the refinery. A mining crawler hauls ore between the sites — it is armoured, slow, and worth a fortune in salvage. Dragoon artillery sits on the ridges. Expect sandstorms: when they roll in, your scanner range collapses.',
      narration: 'Vesper, the Choir are strip-mining the Hadal Flats. Three drill rigs and a refinery. Wreck them all. They are working captured colonists in pens next to the rigs. Break them out if you can. Dragoon artillery is dug in on the ridges: keep moving when you see the target markers. And watch the sky. When a sandstorm hits, your scanner is nearly blind.',
      threats: ['Dragoon artillery — long-range shells, telegraphed impacts', 'Dune raiders — fast strafing bikes', 'Scarab heavy tanks, sand wyrms', 'Sandstorms — scanner range collapses'],
      intel: ['A fuel depot sits next to the refinery. Destroying it scatters fuel cells.', 'Forward pad Delta in the central dunes.', 'The comm relay in the north calls raider squads.'],
      marks: [{ x: 2600, y: 1200, label: 'RIG 1', col: '#ff9a5a' }, { x: 4600, y: 2000, label: 'RIG 2', col: '#ff9a5a' }, { x: 3600, y: 4600, label: 'RIG 3', col: '#ff9a5a' }, { x: 5400, y: 3600, label: 'REFINERY', col: '#ff9a5a' }, { x: 2600, y: 3200, label: 'FOB', col: '#7dff9a' }],
    },
    rewards: { salvage: 650, tech: 1, unlock: ['apc'] },
    reinforcements: { comms: ['comms'], squads: [['raider', 'raider', 'raider'], ['scarab', 'raider', 'raider'], ['sandwyrm']], from: [{ x: 6200, y: 400 }, { x: 3200, y: 200 }, { x: 6200, y: 5600 }], delay: 8, cooldown: 40, max: 5 },
    lines: {
      w2m1_intro: { t: 'Rigs are spread wide. Pad Delta is mid-field. Mind the ridges: dragoons.', s: 'command' },
      w2m1_pens: { t: "Those are our people in the pens. Blow the fences — they'll run to you.", s: 'command' },
      w2m1_crawler: { t: "Mining crawler on the haul road. Armoured, but it's carrying refined ore. Big salvage.", s: 'command' },
      w2m1_refinery: { t: 'The refinery is the heart of the operation. Drop it and the whole flat goes quiet.', s: 'command' },
    },
    entities: [
      ...L.fob('fob', 2600, 3200),
      ...L.cache(800, 2900, ['fuel', 'ammo']),
      { t: 'struct', k: 'derrick', id: 'rig1', x: 2600, y: 1200 }, { t: 'struct', k: 'derrick', id: 'rig2', x: 4600, y: 2000 }, { t: 'struct', k: 'derrick', id: 'rig3', x: 3600, y: 4600 },
      { t: 'struct', k: 'turret_bunker', x: 2450, y: 1300 }, { t: 'struct', k: 'turret_bunker', x: 2780, y: 1100 },
      { t: 'struct', k: 'turret_bunker', x: 4450, y: 2150 }, { t: 'struct', k: 'turret_bunker', x: 4800, y: 1900 },
      { t: 'struct', k: 'turret_bunker', x: 3450, y: 4500 }, { t: 'struct', k: 'turret_bunker', x: 3800, y: 4720 },
      { t: 'struct', k: 'pen', id: 'pen1', x: 2850, y: 1400 }, { t: 'survivors', id: 'pris1', x: 2850, y: 1400, n: 3, kind: 'prisoner', label: 'CAPTIVE MINERS', caged: 'pen1' },
      { t: 'struct', k: 'pen', id: 'pen2', x: 3350, y: 4750 }, { t: 'survivors', id: 'pris2', x: 3350, y: 4750, n: 3, kind: 'prisoner', label: 'CAPTIVE MINERS', caged: 'pen2' },
      { t: 'zone', id: 'penzone', x: 2850, y: 1400, r: 450 },
      { t: 'struct', k: 'refinery', id: 'refinery', x: 5400, y: 3600 },
      { t: 'struct', k: 'fueldepot', id: 'depot', x: 5150, y: 3900 },
      ...L.outpost('ref', 5400, 3600, { turrets: 4, radius: 210, turret: 'turret_bunker', props: false, garrison: [['scarab', 1, 0, 260], ['raider', 3, -200, 0]] }),
      { t: 'zone', id: 'refzone', x: 5400, y: 3600, r: 600 },
      { t: 'struct', k: 'comms', id: 'comms', x: 3600, y: 500 },
      { t: 'unit', k: 'crawler', id: 'crawler', x: 3000, y: 2400, path: [[4400, 2400], [5000, 3200], [4000, 4200], [2800, 3800], [2400, 2000], [3000, 2400]], active: true, team: 'enemy' },
      { t: 'zone', id: 'haul', x: 3600, y: 3000, r: 900 },
      // dragoons on the ridges
      { t: 'unit', k: 'dragoon', x: 1800, y: 1800 }, { t: 'unit', k: 'dragoon', x: 4000, y: 3200 }, { t: 'unit', k: 'dragoon', x: 5700, y: 2300 }, { t: 'unit', k: 'dragoon', x: 2200, y: 4800 },
      { t: 'unit', k: 'mender', x: 4200, y: 3300 },
      { t: 'unit', k: 'scarab', x: 3400, y: 1600, patrol: [[3400, 1600], [4300, 1300], [4100, 2600]] },
      { t: 'zone', id: 'oasis', x: 6000, y: 600, r: 200 },
      ...L.cache(6000, 600, ['tech', 'repair', 'special', 'fuel'], { hidden: true }),
      { t: 'unit', k: 'sandwyrm', x: 5800, y: 900, burrowed: true },
      { t: 'scatter', what: 'unit', k: 'raider', n: 6, size: [2, 3], area: [600, 400, 6200, 5600], seed: 41 },
      { t: 'scatter', what: 'unit', k: 'sandwyrm', n: 3, burrowed: true, area: [600, 600, 6000, 5400], seed: 42 },
      { t: 'scatter', what: 'unit', k: 'sentry', n: 3, size: [2, 2], area: [1500, 400, 6000, 5400], seed: 43 },
      { t: 'scatter', what: 'pickup', k: 'fuel', n: 11, area: [300, 300, 6100, 5700], seed: 44 },
      { t: 'scatter', what: 'pickup', ks: ['ammo', 'missiles', 'salvage', 'repair', 'shield', 'salvage'], n: 14, area: [300, 300, 6100, 5700], seed: 45 },
      { t: 'scatter', what: 'obstacle', n: 22, h: [60, 110], seed: 46 },
      { t: 'scatter', what: 'prop', n: 40, cluster: 2, seed: 47 },
    ],
    objectives: [
      { id: 'rigs', type: 'destroy', targets: ['rig1', 'rig2', 'rig3'], text: 'Destroy the drill rigs', short: 'Destroy the three drill rigs' },
      { id: 'refinery', type: 'destroy', targets: ['refinery'], text: 'Destroy the refinery', short: 'Destroy the refinery' },
      { id: 'prisoners', type: 'rescue', groups: ['pris1', 'pris2'], required: 4, text: 'Free the captive miners', short: 'Rescue the captive miners', cat: 'secondary', reward: 250 },
      { id: 'crawler', type: 'kill', targets: ['crawler'], text: 'Destroy the mining crawler', short: 'Destroy the mining crawler', cat: 'secondary', reward: 200 },
      { id: 'comms', type: 'destroy', targets: ['comms'], text: 'Destroy the comm relay', short: 'Destroy the comm relay', cat: 'secondary', reward: 120 },
      { id: 'oasis', type: 'discover', zone: 'oasis', text: 'Find the smugglers\' oasis cache', short: 'Find the smugglers\' cache', cat: 'hidden' },
    ],
    triggers: [
      { when: { time: 3 }, do: [{ say: 'w2m1_intro' }] },
      { when: { enter: 'penzone' }, do: [{ say: 'w2m1_pens' }] },
      { when: { enter: 'haul' }, do: [{ say: 'w2m1_crawler' }] },
      { when: { enter: 'refzone' }, do: [{ say: 'w2m1_refinery' }] },
      { when: { time: 50 }, do: [{ weather: { sandstorm: true } }] },
    ],
  });

  AS.Levels.add({
    id: 'w2m2', world: 2, index: 2, name: 'IRON CARAVAN', region: 'Scour Canyon',
    map: { w: 6800, h: 5200, seed: 53 },
    start: { x: 600, y: 2700, angle: 0 },
    extraction: { x: 6200, y: 2600, r: 75 },
    briefing: {
      tagline: 'Escort three ore haulers through Scour Canyon.',
      danger: 3,
      situation: 'Three FRC ore haulers must cross Scour Canyon to reach Fort Varn on the eastern rim. Their cargo is the refined Choir alloy we need for your next generation of hardware. The canyon is a shooting gallery: raider ambushes, Dragoon artillery on the rims, a sand wyrm nest at the narrows and a Choir blockade at the eastern gate. The convoy halts whenever hostiles block the road. Fly ahead, clear the route, and keep at least two haulers alive.',
      narration: 'Vesper, three ore haulers are crossing Scour Canyon to Fort Varn. That alloy is going straight into your next upgrades, so keep them alive. At least two must arrive. The convoy stops when hostiles block the road. Scout ahead and clear the way. Expect raiders, artillery on the rim, wyrms at the narrows, and a Choir blockade at the eastern gate.',
      threats: ['Raider ambush squads along the canyon', 'Dragoon artillery battery on the north rim', 'Sand wyrm nest at the narrows', 'Choir blockade turrets at the eastern gate'],
      intel: ['The convoy rolls out a few seconds after you launch. Fly ahead of it.', 'Fort Varn has a pad for repair and resupply.', 'Destroying the artillery battery makes the canyon much safer.'],
      marks: [{ x: 2600, y: 2400, label: 'NARROWS', col: '#ff9a5a' }, { x: 3600, y: 1400, label: 'ARTY', col: '#ff9a5a' }, { x: 5400, y: 2600, label: 'GATE', col: '#ff9a5a' }, { x: 6200, y: 2600, label: 'FORT', col: '#7dff9a' }],
    },
    rewards: { salvage: 700, tech: 2, unlock: ['swarm'] },
    reinforcements: { comms: ['gate_comms'], squads: [['raider', 'raider', 'raider', 'raider'], ['scarab', 'raider']], from: [{ x: 3400, y: 200 }, { x: 4400, y: 5000 }], delay: 6, cooldown: 35, max: 6 },
    lines: {
      w2m2_intro: { t: 'Convoy rolls on my mark. Get ahead of them and keep that road clear.', s: 'command' },
      w2m2_go: { t: 'Convoy is moving. Haulers, keep your spacing.', s: 'command' },
      w2m2_ambush1: { t: 'Raiders! Ambush on the south rim!', s: 'command' },
      w2m2_narrows: { t: 'Seismic movement at the narrows. Wyrms.', s: 'ship' },
      w2m2_gate: { t: "Choir blockade at the gate. The convoy can't pass until those turrets are gone.", s: 'command' },
      w2m2_arrived: { t: 'Hauler has reached Fort Varn.', s: 'command' },
    },
    entities: [
      { t: 'zone', id: 'startpad', x: 700, y: 2650, r: 140 },
      { t: 'convoy', id: 'convoy', units: ['hauler', 'hauler', 'hauler'], team: 'player', x: 900, y: 2700, spacing: 70, start: false,
        path: [[1400, 2700], [2000, 2550], [2600, 2400], [3200, 2600], [3800, 2800], [4400, 2700], [5000, 2600], [5600, 2600], [6100, 2600]] },
      { t: 'struct', k: 'pad', id: 'fort', x: 6200, y: 2450, pad: { repair: true, refuel: true, rearm: true, dropoff: true } },
      { t: 'zone', id: 'amb1', x: 1800, y: 2700, r: 300 }, { t: 'zone', id: 'narrows', x: 2700, y: 2450, r: 380 }, { t: 'zone', id: 'amb2', x: 4100, y: 2800, r: 350 }, { t: 'zone', id: 'gate', x: 5200, y: 2600, r: 500 },
      // artillery battery on the north rim
      { t: 'unit', k: 'dragoon', id: 'art1', x: 3400, y: 1350 }, { t: 'unit', k: 'dragoon', id: 'art2', x: 3700, y: 1450 }, { t: 'unit', k: 'dragoon', id: 'art3', x: 4000, y: 1300 },
      { t: 'unit', k: 'mender', x: 3700, y: 1200 }, { t: 'struct', k: 'turret_bunker', x: 3600, y: 1600 }, { t: 'struct', k: 'radar', id: 'artradar', x: 3900, y: 1100 },
      // wyrm nest at the narrows
      { t: 'unit', k: 'sandwyrm', x: 2600, y: 2200, burrowed: true }, { t: 'unit', k: 'sandwyrm', x: 2900, y: 2700, burrowed: true },
      // the eastern gate blockade
      ...L.outpost('gate', 5300, 2600, { turrets: 4, radius: 180, turret: 'turret', shield: true, shieldAt: [100, -260], powerAt: [200, 300], props: false, garrison: [['thrall', 4, -100, 0], ['shardback', 1, 0, 0]] }),
      { t: 'struct', k: 'comms', id: 'gate_comms', x: 5600, y: 2200 },
      { t: 'zone', id: 'wreck', x: 1600, y: 4600, r: 200 },
      { t: 'struct', k: 'wreckship', x: 1600, y: 4600 },
      ...L.cache(1680, 4660, ['tech', 'salvage', 'missiles'], { hidden: true }),
      { t: 'scatter', what: 'pickup', k: 'fuel', n: 10, area: [300, 300, 6500, 4900], seed: 54 },
      { t: 'scatter', what: 'pickup', ks: ['ammo', 'missiles', 'repair', 'shield', 'salvage'], n: 12, area: [300, 300, 6500, 4900], seed: 55 },
      { t: 'scatter', what: 'unit', k: 'raider', n: 4, size: [2, 3], area: [1500, 400, 6000, 4800], seed: 56 },
      { t: 'scatter', what: 'obstacle', n: 24, h: [60, 110], seed: 57 },
      { t: 'scatter', what: 'prop', n: 30, cluster: 2, seed: 58 },
    ],
    objectives: [
      { id: 'escort', type: 'escort', convoy: 'convoy', required: 2, text: 'Escort the haulers to Fort Varn', short: 'Get at least 2 haulers to Fort Varn', desc: 'The convoy stops when hostiles are near the road.', marker: 'CONVOY' },
      { id: 'arty', type: 'kill', targets: ['art1', 'art2', 'art3'], text: 'Destroy the Dragoon battery', short: 'Destroy the artillery battery', cat: 'secondary', reward: 200 },
      { id: 'gate', type: 'destroy', targets: ['gate_t0', 'gate_t1', 'gate_t2', 'gate_t3'], text: 'Break the eastern blockade', short: 'Destroy the blockade turrets', cat: 'secondary', reward: 150 },
      { id: 'wreck', type: 'discover', zone: 'wreck', text: 'Find the buried crawler', short: 'Find the buried crawler', cat: 'hidden' },
    ],
    triggers: [
      { when: { time: 2 }, do: [{ say: 'w2m2_intro' }] },
      { when: { time: 9 }, do: [{ convoy: 'convoy', act: 'start' }, { say: 'w2m2_go' }] },
      { when: { enter: 'amb1' }, do: [{ say: 'w2m2_ambush1' }, { wave: { k: 'raider', n: 4, x: 1800, y: 3400, tx: 1900, ty: 2700, say: false } }] },
      { when: { enter: 'narrows' }, do: [{ say: 'w2m2_narrows' }, { spawn: [{ t: 'unit', k: 'sandwyrm', x: 2500, y: 2500, burrowed: true, alert: true }] }] },
      { when: { enter: 'amb2' }, do: [{ wave: { k: 'raider', n: 3, x: 4100, y: 3600, tx: 4100, ty: 2800 } }, { wave: { k: 'scarab', n: 1, x: 4400, y: 3700, tx: 4300, ty: 2800, say: false } }] },
      { when: { enter: 'gate' }, do: [{ say: 'w2m2_gate' }] },
      { when: { convoyArrived: 'convoy' }, do: [{ say: 'w2m2_arrived' }] },
      { when: { time: 70 }, do: [{ weather: { sandstorm: true } }] },
    ],
  });

  AS.Levels.add({
    id: 'w2m3', world: 2, index: 3, name: 'THE DEEP MOUTH', region: 'Kharad Basin', boss: true,
    map: { w: 6400, h: 6400, seed: 67 },
    start: { x: 3200, y: 5900, angle: -Math.PI / 2 },
    extraction: { x: 3200, y: 6060, r: 75 },
    briefing: {
      tagline: 'Hunt the giant tunnelling creature beneath the Kharad Basin.',
      danger: 4,
      situation: 'Something has been swallowing mining stations whole. The miners call it Kharad: a sand-serpent hundreds of metres long that breaches without warning and dives before anything can lock on. Its hide shrugs off cannon fire. The abandoned Kharad depot still holds three seismic demolition charges. Carry them to the three tunnel vents the creature uses; each detonation will drive it to the surface, stunned, at that vent. That is your window.',
      narration: 'Vesper, the miners call it Kharad. A sand-serpent that breaches, crushes, and dives before you can lock on. Its hide shrugs off cannon fire. The Kharad depot still has three seismic charges. Fly them to the tunnel vents. Every charge you detonate will drive the beast to the surface, stunned, right at that vent. Hit it while it is down. There may be miners still trapped at the depot.',
      threats: ['KHARAD — colossal breaching sand-serpent', 'Sand wyrms, dune raiders', 'Dragoon artillery', 'Sandstorms'],
      intel: ['Seismic charges are stored at the depot in the west.', 'The three vents ring the basin centre.', 'Cargo clamps hold two charges at once.'],
      marks: [{ x: 1300, y: 3200, label: 'DEPOT', col: '#7fe8ff' }, { x: 2600, y: 2400, label: 'V1', col: '#ffc35a' }, { x: 3900, y: 2200, label: 'V2', col: '#ffc35a' }, { x: 3300, y: 3600, label: 'V3', col: '#ffc35a' }],
    },
    rewards: { salvage: 900, tech: 3 },
    reinforcements: { comms: ['comms'], squads: [['raider', 'raider', 'raider'], ['sandwyrm']], from: [{ x: 6200, y: 400 }], delay: 8, cooldown: 45, max: 4 },
    lines: {
      w2m3_intro: { t: 'Depot is west. Grab the charges and get them into the vents. And Vesper — it already knows you are here.', s: 'command' },
      w2m3_depot: { t: "Charges located. They're stable — mostly.", s: 'ship' },
      w2m3_charge: { t: 'Charge placed. Detonation in three seconds!', s: 'ship' },
      kharad_stunned: { t: "It's down! Hit the head before it dives!", s: 'command' },
      w2m3_miners: { t: 'Over here! The depot! It took the whole shift!', s: 'survivor', name: 'DEPOT MINER' },
      w2m3_dead: { t: 'Kharad is dead. Every miner on this planet owes you a drink.', s: 'command' },
    },
    entities: [
      ...L.fob('fob', 4900, 4600),
      { t: 'struct', k: 'station', id: 'depot', x: 1300, y: 3200, invuln: true },
      { t: 'cargo', k: 'charge', id: 'ch1', x: 1380, y: 3300, deliver: 'v1', label: 'SEISMIC CHARGE', respawn: 30 },
      { t: 'cargo', k: 'charge', id: 'ch2', x: 1420, y: 3260, deliver: 'v2', label: 'SEISMIC CHARGE', respawn: 30 },
      { t: 'cargo', k: 'charge', id: 'ch3', x: 1340, y: 3350, deliver: 'v3', label: 'SEISMIC CHARGE', respawn: 30 },
      { t: 'survivors', id: 'miners', x: 1200, y: 3300, n: 4, kind: 'crew', label: 'DEPOT MINERS', voice: false },
      { t: 'zone', id: 'depotzone', x: 1300, y: 3200, r: 400 },
      { t: 'struct', k: 'vent', id: 'vent1', x: 2600, y: 2400 }, { t: 'zone', id: 'v1', x: 2600, y: 2400, r: 50, marker: true, label: 'VENT 1', lure: 'kharad' },
      { t: 'struct', k: 'vent', id: 'vent2', x: 3900, y: 2200 }, { t: 'zone', id: 'v2', x: 3900, y: 2200, r: 50, marker: true, label: 'VENT 2', lure: 'kharad' },
      { t: 'struct', k: 'vent', id: 'vent3', x: 3300, y: 3600 }, { t: 'zone', id: 'v3', x: 3300, y: 3600, r: 50, marker: true, label: 'VENT 3', lure: 'kharad' },
      { t: 'boss', k: 'kharad', id: 'kharad', x: 3200, y: 2900, wake: 900, introLine: 'boss_warning', deathLine: 'w2m3_dead' },
      { t: 'struct', k: 'comms', id: 'comms', x: 5400, y: 1000 },
      { t: 'struct', k: 'turret_bunker', x: 5300, y: 1150 }, { t: 'struct', k: 'turret_bunker', x: 5550, y: 1100 },
      { t: 'unit', k: 'dragoon', x: 1800, y: 1200 }, { t: 'unit', k: 'dragoon', x: 4800, y: 3000 },
      { t: 'scatter', what: 'unit', k: 'raider', n: 5, size: [2, 3], area: [600, 400, 6000, 5200], seed: 61 },
      { t: 'scatter', what: 'unit', k: 'sandwyrm', n: 3, burrowed: true, area: [600, 600, 6000, 5000], seed: 62 },
      { t: 'scatter', what: 'pickup', k: 'fuel', n: 11, area: [300, 300, 6100, 6000], seed: 63 },
      { t: 'scatter', what: 'pickup', ks: ['ammo', 'missiles', 'repair', 'shield', 'salvage', 'special'], n: 14, area: [300, 300, 6100, 6000], seed: 64 },
      { t: 'scatter', what: 'obstacle', n: 20, h: [60, 110], seed: 65 },
      { t: 'scatter', what: 'prop', n: 30, cluster: 2, seed: 66 },
    ],
    objectives: [
      { id: 'kharad', type: 'boss', targets: ['kharad'], text: 'Kill Kharad — drive it up with seismic charges', short: 'Kill Kharad, the Deep Mouth', marker: 'KHARAD' },
      { id: 'miners', type: 'rescue', groups: ['miners'], required: 3, text: 'Rescue the depot miners', short: 'Rescue the depot miners', cat: 'secondary', reward: 220 },
      { id: 'comms', type: 'destroy', targets: ['comms'], text: 'Destroy the comm relay', short: 'Destroy the comm relay', cat: 'secondary', reward: 120 },
      { id: 'charges', type: 'deliver', items: ['ch1', 'ch2', 'ch3'], required: 3, text: 'Detonate all three seismic charges', short: 'Detonate all three charges', cat: 'secondary', reward: 150 },
    ],
    triggers: [
      { when: { time: 3 }, do: [{ say: 'w2m3_intro' }] },
      { when: { enter: 'depotzone' }, do: [{ say: 'w2m3_depot' }, { say: 'w2m3_miners' }] },
      { when: { delivered: 'ch1' }, do: [{ say: 'w2m3_charge' }] },
      { when: { delivered: 'ch2' }, do: [{ say: 'w2m3_charge' }] },
      { when: { delivered: 'ch3' }, do: [{ say: 'w2m3_charge' }] },
      { when: { time: 90 }, do: [{ weather: { sandstorm: true } }] },
    ],
  });
})(window.AS);
